[package]
name = "iphoto"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.38"
lazy_static = "1.4.0"
regex = "1.7.1"
kamadak-exif = "0.5.5"
sha2 = "0.10.6"
phf = { version = "0.11.1", features = ["macros"] }
glob = "0.3.1"
filetime = "0.2.19"
chrono = "0.4.23"
clap = { version = "4.1.4", features = ["derive"] }
walkdir = "2.3.2"
plist = "1.4.0"
serde = { version = "1.0.152", features = ["derive", "serde_derive"] }


[dev-dependencies]
assert_matches = "1.5.0"
hex-literal = "0.3.4"
