[package]
name = "is-photos"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
regex = "1.7.1"
kamadak-exif = "0.5.5"
sha2 = "0.10.6"
phf = { version = "0.11.1", features = ["macros"] }

[dev-dependencies]
assert_matches = "1.5.0"
hex-literal = "0.3.4"
